# Generated by Django 4.2.3 on 2023-07-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutsomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyimage', models.ImageField(upload_to='')),
                ('propertyprice', models.IntegerField()),
                ('propertylocation', models.CharField(max_length=100)),
                ('propertybathroom', models.IntegerField()),
                ('propertybedrooom', models.PositiveIntegerField()),
                ('area_size', models.PositiveIntegerField()),
                ('propertyamenities', models.TextField(max_length=150)),
                ('propertystatus', models.CharField(max_length=50)),
                ('propertydiscription', models.TextField(max_length=150)),
                ('contactInfo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyname', models.CharField(max_length=100)),
                ('propertycategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicelist', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Selledproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selledpro_no', models.IntegerField()),
                ('Properties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Rentelproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availablefrom', models.DateTimeField()),
                ('remain_amount', models.IntegerField()),
                ('nextpayment', models.ImageField(upload_to='')),
                ('nextpaymentduration', models.DurationField()),
                ('Properties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.properties')),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='Property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.property_type'),
        ),
        migrations.CreateModel(
            name='Imagelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='')),
                ('Properties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myadmin.properties')),
            ],
        ),
    ]
