# Generated by Django 4.2.3 on 2023-07-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=50)),
                ('last_name1', models.CharField(max_length=50)),
                ('email1', models.EmailField(max_length=254)),
                ('phone1', models.IntegerField()),
                ('select_service1', models.CharField(max_length=100)),
                ('select_price1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request_for_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('select_service', models.CharField(max_length=100)),
                ('select_price', models.IntegerField()),
                ('comments', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Quick_appoitement',
        ),
    ]
