# Generated by Django 4.2.3 on 2023-07-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate_App', '0003_properties_property_type_selledproperty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
