# Generated by Django 4.2.3 on 2023-07-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate_App', '0004_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=50)),
                ('pictures', models.ImageField(upload_to='')),
            ],
        ),
    ]
