# Generated by Django 4.2.3 on 2023-07-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate_App', '0005_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apointment',
            name='select_price1',
        ),
        migrations.RemoveField(
            model_name='apointment',
            name='select_service1',
        ),
        migrations.AlterField(
            model_name='property_type',
            name='propertyname',
            field=models.CharField(max_length=150),
        ),
    ]
