# Generated by Django 4.2.3 on 2023-07-15 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate_App', '0007_remove_request_for_contact_select_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutsomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='properties',
            name='Property_type',
        ),
        migrations.AlterField(
            model_name='rentelproperty',
            name='Properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RealEstate_App.property_detail'),
        ),
        migrations.AlterField(
            model_name='selledproperty',
            name='Properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RealEstate_App.property_detail'),
        ),
        migrations.DeleteModel(
            name='Imagelist',
        ),
        migrations.DeleteModel(
            name='Properties',
        ),
        migrations.DeleteModel(
            name='Property_type',
        ),
    ]
